### ISSUE TITLE
Parsing the data from JSON

### ISSUE THREAD

**Issue by rowhitswami** [rowhitswami/rowhitswami.github.io#1]
[Git REST API v3](https://developer.github.com/v3/) is used to get the user data from Github. After parsing the data from JSON, please append **username,** **last 4 pull requests** to the element assigned the *id=result*.
Any other suggestions are most welcome. :blush:

**Comment by chawki27000** [comment]
i take this

**Comment by rowhitswami** [comment]
Great work @chawki27000 :blush: 
However, few modifications are needed:
You separated each pull request with
```html
<p>---------------------------------</p>
```
instead, you can make a card for each pull request parsed from the JSON.

Thank you for amazing work :)

**Comment by chawki27000** [comment]
Thank you @rowhitswami :)
Yes i separated each PR with p tag, I will add a stylesheet for more elegant design.
