### ISSUE TITLE
SEO Improvement

### ISSUE THREAD

**Issue by rowhitswami** [rowhitswami/rowhitswami.github.io#10]
Add meta tags to improve search engine optimization.

**Comment by jbmills327** [comment]
@rowhitswami I would like to take a crack at this if it is not spoken for yet.

**Comment by jbmills327** [comment]
I would like to take a crack at this if it is not spoken for yet

**Comment by rowhitswami** [comment]
Yes, go ahead :)

**Comment by sinAshish** [comment]
I created a PR already. Pls check it.

**Comment by vipulgupta2048** [comment]
#15 Improves SEO further. Another PR coming in for Search Engine Optimization.
