### ISSUE TITLE
[Enhancement] Shows only 4 pull request made

### ISSUE THREAD

**Issue by vipulgupta2048** [rowhitswami/rowhitswami.github.io#20]
I recommend that the tool shows all the pull requests that were made in the month of October which are valid for Hacktoberfest 2017. 
I understand that the tool does its job by showing only 4. But wouldn't it be better if you know your entire progress then just a small part of it. 
Just a thought.

**Comment by rowhitswami** [comment]
Thank you @vipulgupta2048 for pointing out...
This issue is resolved :blush:

**Comment by vipulgupta2048** [comment]
Since you see https://hacktoberfest.digitalocean.com/ already show you your entire progress for the same if you reopen the website while logged in.

**Comment by vipulgupta2048** [comment]
I am sorry. I just mentioned this because It shows only 4 here.
![screenshot_2017-10-14_22-12-45](https://user-images.githubusercontent.com/22801822/31577480-e9332510-b12c-11e7-9017-d44eb9896b03.png)

I got 5 according to my profile on GitHub and Hacktoberfest 2017 official website.

**Comment by rowhitswami** [comment]
Would you like to give a try once more? :blush:

**Comment by vipulgupta2048** [comment]
Works like a charm. Setting a record there in "time taken to resolve issues". LOL
Gonna close this one.
