### ISSUE TITLE
Showing both open issues and PR's

### ISSUE THREAD

**Issue by vipulgupta2048** [rowhitswami/rowhitswami.github.io#28]
- According to the heading, it should show only the things that are mentioned.
- Fix the API call

**Comment by sanudatta11** [comment]
@vipulgupta2048 you can take up the issue

**Comment by vipulgupta2048** [comment]
I think its a really good issue for beginners to take up and if no one picks it up. I would be happy to get it done. Until then I think we should we wait. 
I will promote this issue on my end if anyone would like to pick it up. :hatching_chick:

**Comment by Rahul-Vijay** [comment]
I have fixed this issue simply by using a function that returns a Regular Expression.
