### ISSUE TITLE
Show Data in a Card

### ISSUE THREAD

**Issue by rowhitswami** [rowhitswami/rowhitswami.github.io#3]
Thanks for showing interest in this project. I'm happy to see you here.
Our task is to showing parsed each pull request in a card (using HTML & CSS). So show your creativity and get your pull request merged in no time.
Contributing to this project is very easy, please go through [README.md](https://github.com/rowhitswami/rowhitswami.github.io)
Feel free to give any suggestion. :blush:

**Comment by Occult-Dev** [comment]
Yea, I can do this for ya. Give me 30 minutes or so, see if I can whip up something to your liking :)

**Comment by rowhitswami** [comment]
Yes, go ahead.
