### ISSUE TITLE
Add Chart Feature for showing merged , closed and open request

### ISSUE THREAD

**Issue by sanudatta11** [rowhitswami/rowhitswami.github.io#30]
A chart based feature including total merged,open and closed PRs to different repos to be shown.

**Comment by unsuitable001** [comment]
Is this still open?

**Comment by sanudatta11** [comment]
yes

**Comment by unsuitable001** [comment]
Ok. Guide me through what is actually need to be implemented.
As much as I understood, you want something like a bar graph? that shows the number of merged, closed & open PR?
Or, just want to list their number? (e.g 6 merged, 7 closed, 2 open)

& Your URL is not working by the way..
& The app is not differentiating between `merged` and `closed`... I'll implement that...

**Comment by sanudatta11** [comment]
Cool! Yes I want a graph where people can view the number of merged closed and also month wise contribution.
1. Month Wise - In a Horzizontal Bar Graph
2. As a total - Pie Chart

**Comment by unsuitable001** [comment]
Yep. Almost done! @sanudatta11 
Can I use `mdbootstrap` for displaying the chart?

**Comment by sanudatta11** [comment]
Sure.

**Comment by unsuitable001** [comment]
![Screenshot from 2019-10-13 18-40-51](https://user-images.githubusercontent.com/26590510/66716239-0a734480-ede9-11e9-9432-023ea9818f52.png)

**Comment by sanudatta11** [comment]
Seems cluttered. Make two charts bar and pie and make them horizontal . The charts should look and feel like a fluent design concept.

**Comment by unsuitable001** [comment]
Horizontal graph for monthly?
I think making another call to api will be a better option for monthly PR calculation than checking many items from total items & comparing it.

**Comment by sanudatta11** [comment]
Whatever you seem fine do it. Put a PR I will accept it.
