### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by rowhitswami** [rowhitswami/rowhitswami.github.io#4]
This page has no design till now. So grab this opportunity and do any changes that make the UI appealing to the user.
Don't use any other framework except Bootstrap.

**Comment by quinn-joyce** [comment]
I'll take this

**Comment by vipulgupta2048** [comment]
#15 Improves UI and other features in the website

**Comment by marcowright** [comment]
I can improve the style.

**Comment by rowhitswami** [comment]
@marcowright please go ahead.

**Comment by Barathwaja** [comment]
let me try bro .. @rowhitswami ...  shall i use some other Framework or you need only Bootstrap??

**Comment by rowhitswami** [comment]
@Barathwaja This application should be light-weight as well as responsive. Do make the change if you
think your solution can fulfill this requirement.
