### ISSUE TITLE
JS implementation improvement

### ISSUE THREAD

**Issue by willypt** [rowhitswami/rowhitswami.github.io#6]
- Currently the apps does not check for invalid users or when the said PR is "empty"
- To support more "data" available for the card UI, let's load the user and PR items separately.
- Better Separation of Concern for javascript functions by separating which functions do "dom printing", "requesting data", or "manage callbacks"

**Comment by willypt** [comment]
PR opened at #5

**Comment by rowhitswami** [comment]
Yes for PR opened at #5, Please resolve the merge conflict.
&bull; I added the message for the empty response, please review the updated version.
And you're always welcome to enhance this project. Do whatever you think would be the best for this project.
Thank you @willypt for your great work. :blush:

**Comment by willypt** [comment]
@rowhitswami Hi Rohit, can you please check again?
The source code change would be very big for this PR, sorry about that 😭
